name: 11ty build
'on':
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout last commit of repository
        uses: actions/checkout@v3
      - name: Do Eleventy
        uses: extrawitz/11ty-dockerless-build@v1
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
