name: 11ty build
'on':
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout last commit of repository
        uses: actions/checkout@v3
      - name: Stuff
        uses: extrawitz/11ty-dockerless-build@v1
      - name: deploy
        id: debloyment
        uses: actions/deploy-pages@v4 

