name: 11ty build
'on':
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout last commit of repository
        uses: actions/checkout@v3
      - name: Stuff
        uses: extrawitz/11ty-dockerless-build@v1
      - name: Archive artifact
        shell: sh
        if: runner.os == 'Linux'
        run: |
            tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
        env:
          INPUT_PATH: ${{ inputs.path }}
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error
      - name: deploy
        id: debloyment
        uses: actions/deploy-pages@v4 

